# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d88bb4717b2f581a0e5170a2d75790238cd1f93fedbf81d4b003f88f9a6896e5a62f09987f3a52b08642e197cc1afe270e76862f84d73a0d645cae97eef0336

test:
  secret_key_base: c1094cad8673e287e01519933f5e26e19ad6966251be4763d16db206aaedf0f23d5e9bceaa3e6983e6b40ba68b727ae3fec6cabc06e8f04826ee2732c57dda76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
